HOST = "192.168.75.13"

Vagrant.configure(2) do |config|

  if ENV['IS_DOCKER'] == 'true'
	config.vm.box = "ubuntu/jammy64"
	config.vm.box_version = "20240117.0.0"
  else
    config.vm.box = "debian/bookworm64"
    config.vm.box_version = "12.20241217.1"
  end

  config.vm.box_check_update = false

  config.vm.network "private_network", ip: HOST

  config.vm.synced_folder ".", "/sipmediagw", type: "virtualbox",  owner: "vagrant", group: "vagrant"

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
      vb.cpus = 4
  end

  config.ssh.forward_agent = true

   # Enable provisioning with a shell script
  config.vm.provision "shell", type: "shell" do |s|
    s.env = {
	  "HOST_IP" => HOST,
	  "BROWSING" => ENV["BROWSING"],
	  "IS_DOCKER" => ENV["IS_DOCKER"]
	}
	s.inline = "/sipmediagw/deploy/provision.sh"
  end
  # Set a specific VM name
  config.vm.provider "virtualbox" do |v|
    v.name = "SIPMediaGW_AllInOne"
  end
end
