volumes:
  kamailio_db:

services:
  sip_server:
    image: kamailio4sipmediagw
    build:
      context: kamailio
    container_name: kamailio
    network_mode: host
    logging:
      driver: syslog
      options:
        tag: "kamailio"
    env_file:
      - .env_kamailio
      - ./kamailio/config/.env_cred
      - .env_mysql
    depends_on:
      sip_db:
        condition: service_healthy
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "printenv > /etc/environment &&
         cron && kamailioRun"

  sip_db:
    container_name: kamailioDB
    image: mysql
    volumes:
      - kamailio_db:/var/lib/mysql
      - ./kamailio/db_healthcheck.sh:/usr/local/bin/db_healtcheck
    networks:
      - default
    env_file:
      - .env_mysql
    ports:
      - "3306:3306"
    logging:
      driver: syslog
      options:
        tag: "kamailioDB"
    healthcheck:
      test: "db_healtcheck"
      interval: 5s
      timeout: 5s
      retries: 5

  scaler:
    image: scaler4sipmediagw
    restart: "unless-stopped"
    build:
      context: scaler
    container_name: scaler
    volumes:
      - ./scaler/config:/var/config
      - ./scaler/outscale/config:/var/outscale/config
    network_mode: host
    logging:
      driver: syslog
      options:
        tag: "scaler"
    depends_on:
      sip_db:
        condition: service_healthy
    environment:
      TZ: "Europe/Paris" # Time Zone
      SCALER_CONFIG_FILE: "scaler.json"
      CSP_NAME: "outscale"
      CSP_CONFIG_FILE: "sipmediagw_staging.json"
      CSP_PROFILE: "visio-dev"
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "scaler &
         python webService.py"

  turn_server:
    image: coturn4sipmediagw
    build:
      context: coturn
    container_name: coturn
    network_mode: host
    logging:
      driver: syslog
      options:
        tag: "coturn"
    env_file:
      - .env_turn
      - ./coturn/.env_cred
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "coturnRun"

