volumes:
  kamailio_db:

services:
  sip_server:
    image: kamailio4sipmediagw
    build:
      context: kamailio
    container_name: kamailio
    network_mode: host
    logging:
      driver: syslog
      options:
        tag: "kamailio"
    env_file:
      - .env
      - .env_kamailio
      - .env_mysql
    depends_on:
      sip_db:
        condition: service_healthy
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "printenv > /etc/environment &&
         cron && kamailioRun"

  sip_db:
    container_name: kamailioDB
    image: mysql
    volumes:
      - kamailio_db:/var/lib/mysql
      - ./kamailio/db_healthcheck.sh:/usr/local/bin/db_healtcheck
    env_file:
      - .env_mysql
    ports:
      - "3306:3306"
    logging:
      driver: syslog
      options:
        tag: "kamailioDB"
    healthcheck:
      test: "db_healtcheck"
      interval: 5s
      timeout: 5s
      retries: 5

  scaler:
    image: scaler4sipmediagw
    restart: "unless-stopped"
    build:
      context: scaler
    container_name: scaler
    volumes:
      - ./scaler/config:/var/config
      - ./scaler/scalerTest.py:/var/scalerTest.py
      - ./scaler/outscale/config:/var/outscale/config
    network_mode: host
    logging:
      driver: syslog
      options:
        tag: "scaler"
    depends_on:
      sip_db:
        condition: service_healthy
    environment:
      TZ: "${HOST_TZ}" # Time Zone
    entrypoint:
      - "python"
      - "/var/scalerTest.py"

  turn_server:
    image: coturn4sipmediagw
    build:
      context: coturn
    container_name: coturn
    network_mode: host
    logging:
      driver: syslog
      options:
        tag: "coturn"
    env_file:
      - .env
      - .env_turn
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "coturnRun"

