name: Python CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      
      - run: pip install -r requirements-dev.txt
      - run: pip install pytest ruff
      
      - name: Ruff lint
        continue-on-error: true
        run: ruff check .

      - run: pytest